reddit_clone_proj/reddit_app/urls.py
from django.urls import path
from . import views

app_name = "reddit_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("create-post/", views.create_post, name="create_post"),
    path("trending/", views.create_post, name="trending"),
    path("post/<int:post_id>/", views.single_post, name="single_post"),
    path("post/<int:post_id>/comment", views.comment, name="comment"),
    path("profile/", views.profile, name="profile"),
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"),
    path("post/<int:post_id>/update_helper", views.update_post_helper, name="update_post_helper"),
    path("post/<int:post_id>/update", views.update_post, name="update_post"),
    path('post/<int:post_id>/upvote', views.upvote_post, name='upvote_post'),
    path('post/<int:post_id>/downvote', views.downvote_post, name='downvote_post')

]

reddit_clone_proj/reddit_clone_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reddit/', include("reddit_app.urls")),
    path('user/', include("user_app.urls")),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

]

reddit_clone_proj/user_app/urls.py
from django.urls import path
from . import views

app_name = "user_app"

urlpatterns = [
    # path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("settings/", views.settings, name="settings"),
    # path("delete/", views.delete, name="delete"),
    # path("update-password/", views.update_password, name="update_password"),
    path("request-reset-password/", views.request_reset_password, name="request_reset_password"),
    path("reset-password/", views.reset_password, name="reset_password")
]

reddit_clone_proj/reddit_app/models.py
from enum import unique
from django.db import IntegrityError
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def upvote(self, user):
        try:
            self.vote_set.create(user=user, post=self, vote_type=True)
            self.votes += 1
            self.save()
        except IntegrityError:
            vote = self.vote_set.filter(user=user)
            if vote[0].vote_type == False:
                vote.update(vote_type=True)
                self.votes += 2
                self.save()
            else:
                return 'already_upvoted'
        return 'ok'

    def downvote(self, user):
        try:
            self.vote_set.create(user=user, post=self, vote_type=False)
            self.votes -= 1
            self.save()
        except IntegrityError:
            vote = self.vote_set.filter(user=user)
            if vote[0].vote_type == True:
                vote.update(vote_type=False)
                self.votes -= 2
                self.save()
            else:
                return 'already_downvoted'
        return 'ok'

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    vote_type = models.BooleanField()

    class Meta:
        unique_together = ('user', 'post')

class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

reddit_clone_proj/reddit_app/views.py
from django.shortcuts import render, get_object_or_404, redirect

import reddit_app
from .models import Post, Comment, Vote
from django.contrib.auth.models import User

def index(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, "reddit_app/index.html", {'posts':posts})

def create_post(request):
    user_obj = User.objects.get(pk=1)
    post_obj = Post.objects.create(
                    title="Fav TV Show?",
                    text="List your TV SHow here",
                    author = user_obj
                )
    print(Post.objects.all())
    post = Post.objects.get(pk=11)
    post.comment_set.create(text='Friends', post=post, author=user_obj)    
    post.comment_set.create(text='Others', post=post, author=user_obj)
    post.comment_set.create(text='I dont watch TV  ', post=post, author=user_obj)

    # print(post.comment_set.all())
    return render(request, "reddit_app/index.html", {})

def single_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # print(post.text)
    comments = post.comment_set.all()
    # print(comments)
    return render(request, "reddit_app/single_post.html", {'post':post, 'comments':comments})

def comment(request, post_id):
    if request.method == "POST":
        comment_text = request.POST["comment_text"]
        user_obj = User.objects.get(pk=1)
        post = Post.objects.get(pk=post_id)
        post.comment_set.create(text=comment_text, post=post, author=user_obj)    
    return redirect("reddit_app:single_post", post_id=post_id) 
    
def profile(request):
    user_obj = User.objects.get(pk=1)
    posts = Post.objects.filter(author=user_obj)
    # votes = Vote.objects.filter(user=user_obj).values()
    vote_list = []
    for post in posts:
        try:
            vote = Vote.objects.get(user=user_obj, post=post).vote_type
        except Vote.DoesNotExist:
            vote = None
        vote_list.append(vote)
    posts = zip(posts, vote_list)
    return render(request, 'reddit_app/profile.html', {'posts':posts, 'user':user_obj})

def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect("reddit_app:profile") 

def update_post_helper(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'reddit_app/update_post.html', {'post':post})

def update_post(request, post_id):
    if request.method == "POST":
        title = request.POST["title"]
        text = request.POST["text"]
        Post.objects.filter(pk=post_id).update(title=title, text=text)
    return redirect("reddit_app:profile")

def upvote_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = User.objects.get(pk=1)
    res = post.upvote(user)
    # print(res)
    # print(post.votes)
    # print(Vote.objects.all().values())
    # print(Vote.objects.all().delete())
    return redirect("reddit_app:profile")

def downvote_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = User.objects.get(pk=1)
    res = post.downvote(user)
    # print(res)
    # print(post.votes)
    # print(Vote.objects.all().values())
    # print(post.vote_set.values())
    return redirect("reddit_app:profile")

reddit_clone_proj/templates/reddit_app/index.html
<div>
    {% if posts.count %}
        {% for post in posts %}
            <p> {{ post.title }} </p>
            <p> {{ post.text }} </p>
            <p> {{ post.created_at }} </p>
            <p> {{ post.votes }} </p>
            <p> {{ post.author }} </p>
            <hr>
        {% endfor %}
    {% endif %}
</div>

<div>
    <a href="{% url 'reddit_app:index' %}">
        <h2>New Posts</h2>
    </a>    
    <a href="{% url 'reddit_app:trending' %}">        
        <h2>Trending Posts</h2>
    </a>
</div>

reddit_clone_proj/templates/reddit_app/profile.html
{% load static %} 
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

<div>
    <h2>Welcome, {{user.username}} </h2>
    <p>This is a history of your posts.</p>
</div>

<div>
    <hr>
    {% if posts %}
        {% for post, vote in posts %}
            <p> {{ post.title }} </p>
            <p> {{ post.text }} </p>
            <p> {{ post.created_at }} </p>
            <p> {{ post.votes }} </p>
            <a href="{% url 'reddit_app:delete_post' post.id %}"><button>Delete Post</button></a>
            <a href="{% url 'reddit_app:update_post_helper' post.id %}"><button>Update Post</button></a>
            <br>
            <a href="{% url 'reddit_app:upvote_post' post.id %}" class="{% if vote == True %}upvote{% endif %}" role="button">Upvote</a>
            <a href="{% url 'reddit_app:downvote_post' post.id %}" class="{% if vote == False %}downvote{% endif %}" role="button">Downvote</a>
            <hr>
        {% endfor %}
    {% else %}
        <p>You dont have any posts yet!</p>
    {% endif %}
</div>

reddit_clone_proj/templates/reddit_app/single_post.html
<div>
            <p> {{ post.title }} </p>
            <p> {{ post.text }} </p>
            <p> {{ post.created_at }} </p>
            <p> {{ post.votes }} </p>
            <p> {{ post.author }} </p>
</div>
<hr><br><br><br>
<div>
    {% if comments.count %}
        {% for comment in comments %}
            <p>{{comment.text}}</p>
            <p>{{comment.author}}</p>
            <p>{{comment.created_at}}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>Be the first to comment!</p>
    {% endif %}
</div>
<div>
    <form method="POST" action="{% url 'reddit_app:comment' post.id %}">
        {% csrf_token %}
        <textarea name="comment_text" placeholder="Comment something!"></textarea>
        <button type="submit">Comment</button>
    </form>
</div>

reddit_clone_proj/templates/reddit_app/update_post.html
<div>
    <form method="POST" action="{% url 'reddit_app:update_post' post.id %}">
        {% csrf_token %}
        <input type="text" value="{{post.title}}" name="title"/>
        <textarea name="text">{{post.text}}</textarea>
        <button type="submit">Update</button>
    </form>
</div>