reddit_clone_proj/reddit_clone_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reddit/', include("reddit_app.urls")),
    path('user/', include("user_app.urls")),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

]

reddit_clone_proj/user_app/urls.py
from django.urls import path
from . import views

app_name = "user_app"

urlpatterns = [
    # path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    # path("settings/", views.settings, name="settings"),
    # path("delete/", views.delete, name="delete"),
    # path("update-password/", views.update_password, name="update_password"),
    path("request-reset-password/", views.request_reset_password, name="request_reset_password"),
    path("reset-password/", views.reset_password, name="reset_password")
]

reddit_clone_proj/user_app/models.py
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django_rest_passwordreset.signals import reset_password_token_created
from django.core.mail import send_mail  
from django.conf import settings


@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):

    email_plaintext_message = "Please copy+paste this token {} into the website for resetting your password".format(reset_password_token.key)

    send_mail("Password Reset for {title}".format(title="your reddit-clone account"),
        email_plaintext_message,
        settings.EMAIL_HOST_USER,
        [reset_password_token.user.email]
    )

reddit_clone_proj/user_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login as sess_login, logout as sess_logout
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
import requests

def signup(request):
    context = {}
    if request.user.is_authenticated:
        return redirect("reddit_app:index")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]
        email = request.POST["email"]

        if password == confirm_password:
            try:
                user = User.objects.create_user(username, email, password)
                sess_login(request, user)
                return redirect("reddit_app:index")
            except IntegrityError:
                context = { "error": "Username or email already taken, please try again" }
        else:
            context = {"error" : "Passwords dont match, please try again"}
    return render(request, "user_app/signup.html", context)

def login(request):
    context = {}
    if request.user.is_authenticated:
        return redirect("reddit_app:index")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            sess_login(request, user)
            return redirect("reddit_app:index")
        else:
            context = {"error" : "Invalid Username and Password Combination"}
    return render(request, "user_app/login.html", context)


# def signin(request):
#     return render(request, "user_app/login.html", {})

# def settings(request):
#     return render(request, "user_app/login.html", {})

def logout(request):
    # print(User.objects.all())
    sess_logout(request)
    return redirect("reddit_app:index")

# def delete(request):
#     return render(request, "user_app/login.html", {})

# def update_password(request):
#     return render(request, "user_app/login.html", {})

def request_reset_password(request):
    context = {}
    if request.method == "POST":
        email = request.POST["email"]
        is_email_valid = User.objects.filter(email=email).exists()
        if is_email_valid:
            # context = { "message" : "An email with directions to reset your password has been sent to you! "}
            requests.post("http://127.0.0.1:8000/api/password_reset/",data={"email":email})
            return redirect("user_app:reset_password")
        else:
            context = { "message" : "This email doesnot exist in the Database" }
    return render(request, "user_app/request-reset-password.html", context)

def reset_password(request):
    if request.method == "POST":
        token = request.POST["token"]
        password = request.POST["password"]
        confirm_password = request.POST["confirm_password"]
        if password == confirm_password:
            requests.post("http://127.0.0.1:8000/api/password_reset/confirm/",data={"password":password, "token":token})
            return redirect("user_app:login")
        else:
            return render(request, "user_app/reset_password.html", {"error":"Passwords dont match"})
    return render(request, "user_app/reset_password.html", {})

reddit_clone_proj/templates/user_app/login.html
{% block content %}

<h1>Login</h1>
<hr>

<p>Do not Have an Account?<a href="{% url 'user_app:signup'%}">Create one here</a></p>

<form action="{% url 'user_app:login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"/>
    <input type="password" name="password" placeholder="Password"/>
    <button>Login</button>
</form>

<p>Forgot your password? Reseit it <a href="{% url 'user_app:request_reset_password' %}"> here</a></p>

{% if error %}
    <p>{{ error }}</p>
{% endif %}

{% endblock content %}

reddit_clone_proj/templates/user_app/request-reset-password.html
{% block content %}

<h1> Reset your password </h1>

<form method="POST" action="{% url 'user_app:request_reset_password' %}">
{% csrf_token %}
    <input type="email" name="email" placeholder="Enter your email id"/>
    <button>Reset</button>
</form>

{% if message %}
    <p>{{ message }}</p>
{% endif %}

{% endblock content %}

reddit_clone_proj/templates/user_app/reset_password.html
<form method="POST" action="{% url 'user_app:reset_password' %}">
    {% csrf_token %}
    <input type="text" name="token" placeholder="Enter token"/>
    <input type="password" name="password" placeholder="Enter password">
    <input type="password" name="confirm_password" placeholder="Confirm password">
    <button>Change Password</button>
</form>

{% if error %}
    <p>{{error}}</p>
{% endif%}

reddit_clone_proj/templates/user_app/signup.html
{% block content %}

<h1>Sign up</h1>

<form action="{% url 'user_app:signup' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"/>
    <input type="email" name="email" placeholder="Email"/>
    <input type="password" name="password" placeholder="Password"/>
    <input type="password" name="confirm_password" placeholder="Confirm Password"/>
    <button>SignUp</button>
</form>

{% if error %}
    <p>{{ error }}</p>
{% endif %}
{% endblock content %}